### ISSUE TITLE
No access to /fish deliveries 

### ISSUE THREAD

**Issue by Koekie78** [SalvosGG/issue-tracker#14]
Performing the command:
/fish deliveries
results in:
PyroFishing > You do not have permissions to use this!

Might be because I have the builder role?

Obs

**Comment by Morphiee** [comment]
This is as intended. We may need to mess with it our ask the dev but; The idea is that deliveries will need to be handled by the NPC at /warp fishing

If too many people don't like this concept we can move on to something different but wanted to add a more MMO feel to it instead of sitting in the same spot. Adding player interaction and encouraging players to use the fishing warp together.

**Comment by Koekie78** [comment]
I tried out Fisherman's Island. It looks really nice. I just noticed that you cannot cancel some of the more impossible deliveries. This is quite annoying because it means you cannot get new ones. it says: "You do not have permission to use this!"
