### ISSUE TITLE
Two minor issues with /votefortime

### ISSUE THREAD

**Issue by Koekie78** [SalvosGG/issue-tracker#15]
- When you vote short before it becomes night (cause it turns dark) you get an error, but a bit later when it is really night it says you already voted
- You can vote multiple times: Vote once, log out, log in, vote again. You have voted twice! (This is actually useful when P1ng is afk and you need to pass the night alone)

Obs

**Comment by Morphiee** [comment]
First off can I just say. THANK YOU OBS. I know Crad has used our issue tracker but it so nice to have things tracked for development. Anyways on to the issue;

So I personally haven't been a fan of the current vote for time. It has the bug you mentioned and doesn't account for AFK users. Because of this, I will suggest to the admin team that we look for an alternative "Night Skip" system that is fair and makes more sense. I also want to add that I want to add a system that forces night time. To give those that need/want night time a chance when the server has 30 players concurrently on. If anyone has a plugin suggestion feel free to drop it in here.

**Comment by Morphiee** [comment]
https://www.spigotmc.org/resources/voting-weather-custom.27385/

I think this may be a suitable replacement.
