### ISSUE TITLE
/spawner not working

### ISSUE THREAD

**Issue by Koekie78** [SalvosGG/issue-tracker#20]
I claimed the Spawner Breaker via /spawner. It went on cooldown but I did not get an item. 

Inventory was not full

**Comment by Morphiee** [comment]
https://songoda.com/marketplace/product/epicspawners-the-ultimate-spawner-plugin.13

https://www.spigotmc.org/resources/upgradeable-spawners-spawner-plugin-level-spawner-change-entity-type-1-18-support.77717/

I think I enjoy the songoda plugin more and paired with our Upgradable hoppers plugin we have these things will be good to hopefully limit any performance issue we may hit due to spawners.
