### ISSUE TITLE
Courier delivery does not give a gravestone

### ISSUE THREAD

**Issue by IzzyCos** [SalvosGG/issue-tracker#25]
I'm pretty sure it just needs to be updated to the new gravestone items
![image](https://user-images.githubusercontent.com/103778220/164317236-a38f4467-a1f9-4939-9154-89e25d2d878e.png)

**Comment by Morphiee** [comment]
Most of the Courier rewards were invalid. (Mainly because we swapped a bunch of plugins around.)
All rewards have been buffed and fixed accordingly.

Daily Reward (Everyone) 
- 60 min Shop Advertisement Gem

Normal Delivery (Apollo and Athena) (Pick one)
- 3 Rare Crate keys
- 1 Gravestone
- 250 Experience

Super Delivery (Ares and Hades) (Pick one)
- $7,000
- 3 Fishing Crate keys
- 1 Normal Cubelet (Cosmetic Crate)

Ultra Delivery (Poseidon and Zeus) (Pick one)
- 7 Day Shop Advertisement Gem
- 1 Ultra Crate key
- 100 Tokens
